/**
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **/

#pragma once

#include <stdint.h>

#include "codes.h"
#include "parameters.h"

#ifndef CELERES_TAG_SELF_ORTHOGONAL
#define CELERES_TAG_SELF_ORTHOGONAL 1
#endif

#if CELERES_TAG_SELF_ORTHOGONAL
#define CELERES_TAG_ORDER_BITS_PER_ENTRY BITS_TO_REPRESENT(K - 1)
#define CELERES_TAG_ORDER_BYTES \
    ((K * CELERES_TAG_ORDER_BITS_PER_ENTRY + 7u) / 8u)
#define CELERES_TAG_ROOT_BITS_BYTES ((K + 7u) / 8u)
#define CELERES_TAG_MATRIX_ELEMENTS ((K * (K - 1u)) / 2u)
#define CELERES_TAG_MATRIX_BYTES \
    ((BITS_TO_REPRESENT(Q) * CELERES_TAG_MATRIX_ELEMENTS + 7u) / 8u)
#define CELERES_TAG_BYTES \
    (N8 + CELERES_TAG_ORDER_BYTES + CELERES_TAG_ROOT_BITS_BYTES + \
     CELERES_TAG_MATRIX_BYTES)
#else
#define CELERES_TAG_BYTES RREF_MAT_PACKEDBYTES
#endif

#if CELERES_TAG_SELF_ORTHOGONAL
void celeres_tag_sample_base_rref(uint8_t out[RREF_MAT_PACKEDBYTES],
                                  const uint8_t seed[SEED_LENGTH_BYTES]);

int celeres_tag_compress_from_rref(uint8_t out[CELERES_TAG_BYTES],
                                   const uint8_t rref[RREF_MAT_PACKEDBYTES]);

int celeres_tag_expand_to_rref(uint8_t out[RREF_MAT_PACKEDBYTES],
                               const uint8_t tag[CELERES_TAG_BYTES]);
#endif
