/**
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **/

#pragma once

#include <stdint.h>

#include "parameters.h"

#if N == 16
#define CELERES_PERM_COMPRESSED_BITS 45u
#elif N == 252
#define CELERES_PERM_COMPRESSED_BITS 1657u
#elif N == 272
#define CELERES_PERM_COMPRESSED_BITS 1819u
#elif N == 400
#define CELERES_PERM_COMPRESSED_BITS 2896u
#elif N == 416
#define CELERES_PERM_COMPRESSED_BITS 3035u
#elif N == 548
#define CELERES_PERM_COMPRESSED_BITS 4218u
#elif N == 564
#define CELERES_PERM_COMPRESSED_BITS 4364u
#else
#error "No quasi-optimal permutation-compression parameters for this N"
#endif

#define CELERES_PERM_COMPRESSED_BYTES ((CELERES_PERM_COMPRESSED_BITS + 7u) / 8u)

void celeres_perm_compress(uint8_t out[CELERES_PERM_COMPRESSED_BYTES],
                            const POSITION_T permutation[N]);

int celeres_perm_decompress(POSITION_T permutation[N],
                             const uint8_t in[CELERES_PERM_COMPRESSED_BYTES]);
